Controllers/EnemyController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AbyssRunSite.Models;
using AbyssRunSite.DataAccessLayer;


namespace AbyssRunSite.Controllers
{
    [Authorize]
    public class EnemyController : Controller
    {
        // Database:
        private AbyssContext db = new AbyssContext();

        /// <summary>
        /// Index (for private viewing)
        /// </summary>
        /// <returns></returns>
        public ActionResult Index(string sortOrder, string search)
        {
            ViewBag.SortName = String.IsNullOrEmpty(sortOrder) ? "nameDesc" : "";
            ViewBag.SortHP = sortOrder == "health" ? "healthDesc" : "health";

            var enemies = from e in db.Enemies
                          select e;
            if (!String.IsNullOrEmpty(search))
            {
                enemies = enemies.Where(e => e.EnemyName.Contains(search));
            }

            switch(sortOrder)
            {
                case "nameDesc":
                    enemies = enemies.OrderByDescending(e => e.EnemyName);
                    break;
                case "healthDesc":
                    enemies = enemies.OrderByDescending(e => e.EnemyHP);
                    break;
                case "health":
                    enemies = enemies.OrderBy(e => e.EnemyHP);
                    break;
                default:
                    enemies = enemies.OrderBy(e => e.EnemyName);
                    break;
            }

            return View(enemies.ToList());
        }

        /// <summary>
        /// Display Enemy Info Page (for public viewing).
        /// </summary>
        /// <returns></returns>
        [AllowAnonymous]
        public ActionResult DisplayInfo()
        {
            return View(db.Enemies.ToList());
        }

        /// <summary>
        /// POST Edit Display Info
        /// </summary>
        /// <param name="enemyModel"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditDisplayInfo([Bind(Include = "Id,EnemyHP,EnemyName,EnemyAttack,EnemyDescription,EnemyImageSrc")] EnemyModel enemyModel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(enemyModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("DisplayInfo");
            }

            return View(enemyModel);
        }

        /// <summary>
        /// Edit for the Display Info page.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult EditDisplayInfo(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EnemyModel enemy = db.Enemies.Find(id);
            if (enemy == null)
            {
                return HttpNotFound();
            }

            return View(enemy);
        }

        /// <summary>
        /// Details.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EnemyModel enemy = db.Enemies.Find(id);
            if (enemy == null)
            {
                return HttpNotFound();
            }
            return View(enemy);
        }

        /// <summary>
        /// Create.
        /// </summary>
        /// <returns></returns>
        public ActionResult Create()
        {
            return View();
        }

        // POST: EnemyModels/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,EnemyHP,EnemyName,EnemyAttack,EnemyDescription,EnemyImageSrc")] EnemyModel enemyModel)
        {
            if (ModelState.IsValid)
            {
                db.Enemies.Add(enemyModel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(enemyModel);
        }

        /// <summary>
        /// Edit.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EnemyModel enemyModel = db.Enemies.Find(id);
            if (enemyModel == null)
            {
                return HttpNotFound();
            }
            return View(enemyModel);
        }

        /// <summary>
        /// POST Edit with anti-forgery token.
        /// </summary>
        /// <param name="enemyModel"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,EnemyHP,EnemyName,EnemyAttack,EnemyDescription,EnemyImageSrc")] EnemyModel enemyModel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(enemyModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(enemyModel);
        }

        /// <summary>
        /// Delete.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EnemyModel enemyModel = db.Enemies.Find(id);
            if (enemyModel == null)
            {
                return HttpNotFound();
            }
            return View(enemyModel);
        }

        /// <summary>
        /// Delete Confirmation Page.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            EnemyModel enemyModel = db.Enemies.Find(id);
            db.Enemies.Remove(enemyModel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        /// <summary>
        /// Method to dispose items once connection is closed.
        /// </summary>
        /// <param name="disposing"></param>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity.Infrastructure;

namespace AbyssRunSite.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

    }
}

Controllers/ItemController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AbyssRunSite.Models;
using AbyssRunSite.DataAccessLayer;

namespace AbyssRunSite.Controllers
{
    [Authorize]
    public class ItemController : Controller
    {
        private AbyssContext db = new AbyssContext();

        /// <summary>
        /// Index Page for Items.
        /// </summary>
        /// <returns></returns>
        public ActionResult Index(string sortOrder)
        {
            ViewBag.SortName = String.IsNullOrEmpty(sortOrder) ? "nameDesc" : "";

            var items = from i in db.Items
                        select i;
            switch (sortOrder)
            {
                case "nameDesc":
                    items = items.OrderByDescending(i => i.ItemName);
                    break;
                default:
                    items = items.OrderBy(i => i.ItemName);
                    break;
            }

            return View(items.ToList());
        }

        /// <summary>
        /// Details page for Items
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ItemModel itemModel = db.Items.Find(id);
            if (itemModel == null)
            {
                return HttpNotFound();
            }
            return View(itemModel);
        }

        /// <summary>
        /// Create Page for Items.
        /// </summary>
        /// <returns></returns>
        public ActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// Display Item Info Page (for public viewing).
        /// </summary>
        /// <returns></returns>
        [AllowAnonymous]
        public ActionResult DisplayInfo()
        {
            return View(db.Items.ToList());
        }

        /// <summary>
        /// POST page for Creating Items.
        /// </summary>
        /// <param name="itemModel"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,ItemName")] ItemModel itemModel)
        {
            if (ModelState.IsValid)
            {
                db.Items.Add(itemModel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(itemModel);
        }

        /// <summary>
        /// Edit Page for items.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ItemModel itemModel = db.Items.Find(id);
            if (itemModel == null)
            {
                return HttpNotFound();
            }
            return View(itemModel);
        }

        /// <summary>
        /// POST edit page for items.
        /// </summary>
        /// <param name="itemModel"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,ItemName")] ItemModel itemModel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(itemModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(itemModel);
        }

        /// <summary>
        /// Delete page for items.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ItemModel itemModel = db.Items.Find(id);
            if (itemModel == null)
            {
                return HttpNotFound();
            }
            return View(itemModel);
        }

        /// <summary>
        /// POST delete page for items.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ItemModel itemModel = db.Items.Find(id);
            db.Items.Remove(itemModel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        /// <summary>
        /// Required for IDisposable.
        /// </summary>
        /// <param name="disposing"></param>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/LevelController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AbyssRunSite.Models;
using AbyssRunSite.DataAccessLayer;
using PagedList;

namespace AbyssRunSite.Controllers
{
    [Authorize]
    public class LevelController : Controller
    {
        private AbyssContext db = new AbyssContext();

        // GET: Level
        public ActionResult Index()
        {
            return View(db.Levels.ToList());
        }

        // GET: Level/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LevelModel levelModel = db.Levels.Find(id);
            if (levelModel == null)
            {
                return HttpNotFound();
            }
            return View(levelModel);
        }

        /// <summary>
        /// Display Item Info Page (for public viewing).
        /// </summary>
        /// <returns></returns>
        [AllowAnonymous]
        public ActionResult DisplayInfo(int? page)
        {
            LevelPopulatonViewModel levelInfo = new LevelPopulatonViewModel();

            levelInfo.LevelData = db.Levels.ToList();
            levelInfo.EnemyData = db.Enemies.ToList();
            levelInfo.ItemData = db.Items.ToList();
                       
            return View(levelInfo);
        }

        // GET: Level/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Level/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,LevelName,LevelDescription")] LevelModel levelModel)
        {
            if (ModelState.IsValid)
            {
                db.Levels.Add(levelModel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(levelModel);
        }

        // GET: Level/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LevelModel levelModel = db.Levels.Find(id);
            if (levelModel == null)
            {
                return HttpNotFound();
            }
            return View(levelModel);
        }

        // POST: Level/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,LevelName,LevelDescription")] LevelModel levelModel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(levelModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(levelModel);
        }

        // GET: Level/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LevelModel levelModel = db.Levels.Find(id);
            if (levelModel == null)
            {
                return HttpNotFound();
            }
            return View(levelModel);
        }

        // POST: Level/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            LevelModel levelModel = db.Levels.Find(id);
            db.Levels.Remove(levelModel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Home/About.cshtml
<article class="jumbotron">
    <h1>About</h1>
</article>
<p>Abyss Run is a 2d action platformer that was originally created as a final project for CIT131 at Northwestern Michigan Collage.</p>
<hr/>
<article class="jumbotron" style="background-image: url(../../Content/Images/ScorpuronLogo.png); background-repeat: no-repeat; background-position: center; background-size:30%; background-color:black;">
    <h1>Story</h1>
    <p style="background-color: rgba(51, 44, 53, 0.575);">Long ago in the mists of prehistory, the race of the Scorpuron were created to guard the underworlds of the earth and the secrets thereof. The greatest of these treasures was forged in the first era of man, a sprawling research center that was burried in a catalcysm that brought about the end of those supposedly more enlightened days. The submerging of this facility brought it into the domain of the scorpion folk and the creatures did guard their new charge well throughout the ancient era. Many myths were inspired by the creatures and their charge, but after a time they faded into obscurity as their legends were forgotten and the beings entered hybernation. Until now... </p>
    @*<p><a class="btn btn-default">Read More &raquo;</a></p>*@
</article>
<section class="row">
    <article class="col-md-4">
        <h1>Levels</h1>
        <p>The catacombs of the underworld are hazardous to the extreme. Bring a map...</p>
        @*<p><a class="btn btn-default">Read More &raquo;</a></p>*@
    <p>@Html.ActionLink("Read More", "DisplayInfo", "Level")</p>
    </article>
    <article class="col-md-4">
        <h1>Items</h1>
        <p>The facility has many items that can help Garrison in their quest to reach the surface and escape the facility.</p>
        @*<p><a class="btn btn-default">Read More &raquo;</a></p>*@
        <p>@Html.ActionLink("Read More", "DisplayInfo", "Item")</p>
    </article>
    <article class="col-md-4">
        <h1>Enemies</h1>
        <p>As has been the case since the great cataclysm that brought an end to the first era, many different creatures stalk the halls of the Abyss - most of which are hostile.</p>
        @*<p><a class="btn btn-default">Read More &raquo;</a></p>*@
        <p>@Html.ActionLink("Read More", "DisplayInfo", "Enemy")</p>
    </article>
</section>

Views/Home/Contact.cshtml
<section class="jumbotron"><h1>Contact</h1></section>

<section class="row">
    <article class="col-md-4 row">
        <p>Itch IO: <span class="icon-bar"><a href="https://strategistn8.itch.io/"><i class="fab fa-itch-io"></i></a></span></p>
        <p> You can play the original project here, enjoy!</p>
    </article>
    <article class="col-md-4 row">
        <p>
            NMC IT Facebook:
            <span class="icon-bar"><a href="https://www.facebook.com/CIT.NMC/?ref=bookmarks"><i class="fab fa-facebook-square"></i></a></span>
        </p>
    </article>
    <article class="col-md-4 row">
        <p>Linked In: 
        <span class="icon-bar"><a href="https://www.linkedin.com/in/jameslyons-stratn8/"><i class="fab fa-linkedin"></i></a></span></p>
    </article>
</section>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<section class="jumbotron" style="background-image:url(../../Content/Images/GR03.PNG); background-repeat:no-repeat; background-size:cover;">
    <h1>Abyss Run</h1>
</section>


<hr/>
<section class="row" style="background-color:black; border-radius:10px; background-image:url(../../Content/Images/Glyphs.png); background-repeat:repeat-y; background-size:initial; background-position:right;">

    <img src="~/Content/Images/Screen1.PNG" style="width:25%; height:25%; border: 2px solid darkorange; margin: 2%;border-radius:10px;">

    <img src="~/Content/Images/Screen3.png" style="width:25%; height:25%; border: 2px solid darkorange; margin: 2%;border-radius:10px;">

    <img src="~/Content/Images/Screen2.png" style="width:25%; height:25%; border: 2px solid darkorange; margin: 2%;border-radius:10px;">

    <img src="~/Content/Images/Screen4.PNG" style="width:25%; height:25%; border: 2px solid darkorange; margin: 2%;border-radius:10px;">

    <img src="~/Content/Images/Screen5.PNG" style="width:25%; height:25%; border: 2px solid darkorange; margin: 2%;border-radius:10px;">

    <img src="~/Content/Images/GR04.PNG" style="width:25%; height:25%; border: 2px solid darkorange; margin: 2%;border-radius:10px;">

</section>